# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spix < Formula
  desc ""
  homepage "https://github.com/mauroandocilla/cli-squeezy-pix"
  version "0.1.0-beta.1"

  on_macos do
    url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.1/cli-squeezy-pix_0.1.0-beta.1_darwin_all.tar.gz"
    sha256 "8a6044122aec3b5c0e99f8383f856fd7f6b8d2cb04b243ddd9fccc0fd5f724a3"

    def install
      bin.install "cli-squeezy-pix"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.1/cli-squeezy-pix_0.1.0-beta.1_linux_amd64.tar.gz"
        sha256 "bb13b04db286e507abdc6d07a5b354a6feb212cbc766915169c90f0c497d7942"

        def install
          bin.install "spix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.1/cli-squeezy-pix_0.1.0-beta.1_linux_arm64.tar.gz"
        sha256 "48e34d6c6144946f3b0834fc8b2119dbf86f089bd4a10c7d53f28d86c7dfc244"

        def install
          bin.install "spix"
        end
      end
    end
  end
end
