# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spix < Formula
  desc ""
  homepage "https://github.com/mauroandocilla/cli-squeezy-pix"
  version "0.1.0-beta.1"

  on_macos do
    url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_darwin_all.tar.gz"
    sha256 "3ab3a7ecff7c2355fb2f16c9ae1db7981148f11e16e5fbce9c7d0a17d79dd880"

    def install
      bin.install "homebrew-mauroandocilla"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_linux_amd64.tar.gz"
        sha256 "b39bc230edf5a4abcf65a697aa75fd14daf804f76cd165df725b356f824d3740"

        def install
          bin.install "spix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_linux_arm64.tar.gz"
        sha256 "c3a766934d96eaa59b7e1fb7cf32eb415c3437056bcd1bf911a7f94733797b4a"

        def install
          bin.install "spix"
        end
      end
    end
  end
end
