# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spix < Formula
  desc ""
  homepage "https://github.com/mauroandocilla/cli-squeezy-pix"
  version "0.1.0-beta.1"

  on_macos do
    url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_darwin_all.tar.gz"
    sha256 "f0b53da980256ccf18c43757aba37ee6be55e52044a81d0afb13adcf7d0c397a"

    def install
      bin.install "spix"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_linux_amd64.tar.gz"
        sha256 "47e3ab4f9ef461a42bd148f84ecf866ebfbb5afb779ea0a119315e7fee1911cc"

        def install
          bin.install "spix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_linux_arm64.tar.gz"
        sha256 "b54016d28d5b1cc590e24ee431cb10f554d768d73085aec230b2503f4fa6df84"

        def install
          bin.install "spix"
        end
      end
    end
  end

  test do
    system "#{bin}/spix", "--version"
  end
end
