# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spix < Formula
  desc ""
  homepage "https://github.com/mauroandocilla/cli-squeezy-pix"
  version "0.1.0-beta.3"

  on_macos do
    on_intel do
      url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.3/cli-squeezy-pix_0.1.0-beta.3_darwin_amd64.tar.gz"
      sha256 "a9dab102137c114c663a28e1afb6ed79222a1568ad9ec6f64dd00312fb8b74f9"

      def install
        bin.install "spix"
      end
    end
    on_arm do
      url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.3/cli-squeezy-pix_0.1.0-beta.3_darwin_arm64.tar.gz"
      sha256 "6d3ca54ff791078c289766a86af68ddca3fcd84b495413bf38b02946ff4a22f2"

      def install
        bin.install "spix"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.3/cli-squeezy-pix_0.1.0-beta.3_linux_amd64.tar.gz"
        sha256 "ea63d6fd3669a31d66a22cb202f087bd662548632ddd8311b4188b250cbaac5b"

        def install
          bin.install "spix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.3/cli-squeezy-pix_0.1.0-beta.3_linux_arm64.tar.gz"
        sha256 "270fbf77111268704fadf707277da4240b54838332905b715270be4d897b81ae"

        def install
          bin.install "spix"
        end
      end
    end
  end

  test do
    system "#{bin}/spix", "--version"
  end
end
