# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spix < Formula
  desc ""
  homepage "https://github.com/mauroandocilla/cli-squeezy-pix"
  version "0.1.0-beta.1"

  on_macos do
    url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_darwin_all.tar.gz"
    sha256 "7ecc0ab9c48c174be6b27f0325141953dd7026c7b3698377d8757c8cd1d2e780"

    def install
      bin.install "spix"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_linux_amd64.tar.gz"
        sha256 "4da2417eb1db17f6c3daba30da944a77de768f50db02cc339f926ed684aa71d5"

        def install
          bin.install "spix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/homebrew-mauroandocilla/releases/download/v0.1.0-beta.1/homebrew-mauroandocilla_0.1.0-beta.1_linux_arm64.tar.gz"
        sha256 "ca637644783d01edf71370f5013654fe7fd55c2ba765976d48e06846ea5bef73"

        def install
          bin.install "spix"
        end
      end
    end
  end

  test do
    system "#{bin}/spix", "--version"
  end
end
