# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spix < Formula
  desc ""
  homepage "https://github.com/mauroandocilla/cli-squeezy-pix"
  version "0.1.0-beta.1"

  on_macos do
    on_intel do
      url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.1/cli-squeezy-pix_0.1.0-beta.1_darwin_amd64.tar.gz"
      sha256 "ef57e45f8352fe068f597b48d63913944da48d2e9a49db8ead42fa655f5db2b0"

      def install
        bin.install "spix"
      end
    end
    on_arm do
      url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.1/cli-squeezy-pix_0.1.0-beta.1_darwin_arm64.tar.gz"
      sha256 "c4672b1a88778118f57d734faf68a852fddce4866ba7ea29ea00b9d3f5329740"

      def install
        bin.install "spix"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.1/cli-squeezy-pix_0.1.0-beta.1_linux_amd64.tar.gz"
        sha256 "e1be234093c5d3b2157e54ef65aa813365f09c953f39137de3e676c69b257b7d"

        def install
          bin.install "spix"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/mauroandocilla/cli-squeezy-pix/releases/download/v0.1.0-beta.1/cli-squeezy-pix_0.1.0-beta.1_linux_arm64.tar.gz"
        sha256 "054efdaab1a8d6c4e7b7ba646d40c3bce4d328a7cc955565e1f1872b7b698095"

        def install
          bin.install "spix"
        end
      end
    end
  end

  test do
    system "#{bin}/spix", "--version"
  end
end
